### ISSUE TITLE
An error happened when trying to set the secret.

### ISSUE THREAD

**Issue by enotick** [pantheon-systems/terminus-secrets-manager-plugin#20]
Hello, I am on the newest version of Terminus. And I am trying to add a secret to one of our sites. Running the command:
 terminus secret:set [site].[multidev] github-oauth.github.com [token]--type=composer --scope=user,ic
returns an error "An error happened when trying to set the secret."

Is there anything I can do to debug?
Thanks.

**Comment by greg-1-anderson** [comment]
First, secrets are currently always site-wide, so try `terminus secret set [site]...` instead of `terminus secret set [site].[multidev]...`.

When I tried adding an environment, though, I found that the environment was ignored and the secret was set site-wide. Try running `terminus plugin:list` and make sure that you have version 1.1.0.

If neither of those things lead you to a resolution, try running with `-vvv` and see if that gives extra info that is more informative.

**Comment by namespacebrian** [comment]
Additionally, what version of PHP are you running terminus with?  Are you running terminus on Mac or Windows? 

It's also helpful to list the specific version number of terminus you are running, rather than simply saying "the latest" because the latest version yesterday may not be the latest version tomorrow.

**Comment by enotick** [comment]
@greg-1-anderson @namespacebrian thanks for your help. I was on plugin version 1.0.0 I updated the plugin to version 1.1.0 and remove the environment the secret is now set and I get success message.
