### ISSUE TITLE
Updating existing value.

### ISSUE THREAD

**Issue by dpagini** [pantheon-systems/terminus-secrets-manager-plugin#49]
I'm having an issue updating an existing value. The error message says to use "PATCH" to update an existing value, but I think this is a message coming back from the API, and is not meant for the end user...? I also saw that there's code that looks for this message when a key is attempted to be saved, and then use the PATCH method instead, but that does not appear to be getting hit in my case.

Happy to provide more details if needed, but I guess to reproduce just create a value and then try to update it...?

![image](https://github.com/pantheon-systems/terminus-secrets-manager-plugin/assets/1724163/dc6f4a96-a444-474c-b8ea-27b583509ace)

**Comment by kporras07** [comment]
Hi @dpagini this error is happening because the only thing that could be updated is the value. Type and scope are immutable once set so if you want to update a secret, you should NOT pass those options. Once you remove them, it should work as expected.

Please give it a try and confirm everything is working as expected

**Comment by kporras07** [comment]
Hi @dpagini 

The previous comment still holds but I 100% this was confusing so this was fixed in #50 and a new release was just created.

Once you update the plugin, this error should be clearer.

I'm closing this issue now, feel free to reopen if needed
